# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_goods', '0002_auto_20180127_1351'),
        ('my_user', '0002_auto_20180125_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('acid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('acdate', models.DateTimeField(auto_now=True)),
                ('acIsPay', models.BooleanField(default=False)),
                ('actotle', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acaddres', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_user.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='accountdetailinfo',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountInfo'),
        ),
        migrations.AddField(
            model_name='accountdetailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_goods.Goods'),
        ),
    ]
