# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gclick',
            field=models.IntegerField(default=0),
        ),
    ]
